### ISSUE TITLE
Show today's daily planner does not observe the daily's note template.

### ISSUE THREAD

**Issue by SalahAdDin** [replete/obsidian-day-planner#5]
Hello,

I'm testing this plugin with my template and I am struggling to understand how it does work.

With difficulty, **I realized the Timeline is only shown for today's note(it does not work for future notes, for example, Monday).**

But now, I want to report this bug: **when we use the command `Show today's daily planner` and there is no existing note for it**, it creates a daily note using the correct naming format but forgets to apply the settled template:
![DayPlannerBug1](https://user-images.githubusercontent.com/5034215/221424219-52b7a2fe-57f4-4c14-a629-3fdad593a1c4.gif)

If we create the note from the calendar, it comes fully templated!

What's the problem here?

**Comment by SalahAdDin** [comment]
The interesting thing is every time I open the vault, it automatically created today's note with the correct template, no error here.

And I know it created the note cause I always delete it before closing Obsidian.

**Comment by replete** [comment]
Daily mode makes the plugin automatically search and link to your daily note templates. It does not allow you to look forward or backward. 

In the normal mode, you have to `link` and `unlink` via command, the note to/from dayplanner, so Daily mode does this automatically. 

So in normal mode, you would link it to the note you have open, via a command.

It could be improved in the future, but I'm not likely to do this.

**Comment by SalahAdDin** [comment]
> Daily mode makes the plugin automatically search and link to your daily note templates. It does not allow you to look forward or backward.
> 
> In the normal mode, you have to `link` and `unlink` via command, the note to/from day planner, so Daily mode does this automatically.
> 
> So in normal mode, you would link it to the note you have open, via a command.
> 
> It could be improved in the future, but I'm not likely to do this.

Ok, no problem with it, but if it will create a new note, it should respect the template.

**Comment by replete** [comment]
Daily mode works best, I'd recommend using that.
I create my daily notes either by hotkey or calendar plugin. but its Periodic Notes plugin (replacing Daily Notes) which makes it work.

**Comment by replete** [comment]
So the recommended solution is to use Daily mode, and use another command to create your daily note, that's a job for Daily Note plugin or whatever

**Comment by SalahAdDin** [comment]
> Daily mode works best, I'd recommend using that. I create my daily notes either by hotkey or the calendar plugin. but it is the Periodic Notes plugin (replacing Daily Notes) that makes it work.

I am using that mode actually, I just tested creating tasks from the command line cause at the beginning Obsidian was not responding to the daily notes, or I misunderstood the plugin.

**Comment by replete** [comment]
The plugin should be used like this:
- Install plugin
- Set Daily mode, set daily folder to the folder of your daily notes (containing YYYY-MM-DD formatted filenames, for each day)
- In your daily note template add a heading titled 'Day Planner'
- underneath this heading, in today's daily note, for instance, add tasks prefixed with time like so:
    `- [ ]  08:00 First event`
     `- [ ]  08:30 Second event`
    `...`
- Create your daily note however (periodic notes hotkey / templater / command / etc - not this plugins job) you like, and the plugin should pickup these tasks in the right sidebar
- If you want to see a visual representation of the tasks in the right for a day in the past, you can manually link it to that note (but what is the point of this)
- Each day, the plugin will look for your new daily note matching the current day e.g. /Daily/2023-03-02.md and show the tasks. If the file doesn't exist, it will not create it. When you create it (however you want to) it will pick up the events and display them in the sidebar

That's pretty much the workflow for using this plugin with daily notes. It doesn't create your daily notes for you, it looks for events under a heading in a particular format in your daily note.

**Comment by SalahAdDin** [comment]
Ok, that's the correct way to do that.

But I still think, creating a daily note from the command bar should use the designed template and respect it.
